Sensible Defaults:Builds (#239)
* Setup nightly build schedule as part of "Sensible Defaults:Builds" direction.
* Aligning TestResults directory to display GHA unit test results.
* Aligning scheduled build time to 5am AEST.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,13 +10,16 @@ on:
       - '**'
   schedule:
     # Daily 5am australian/brisbane time
-    - cron: '19 0 * * *'
+    - cron: '0 19 * * *'
     # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+env:
+  OCTOVERSION_CurrentBranch: ${{ github.head_ref || github.ref }} # For pull_request events we override the /refs/pull/xx/merge branch to the PR's head branch
+
 jobs:
   build:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
@@ -27,40 +30,29 @@ jobs:
         with:
           dotnet-version: 6.0.x
 
+      # Adjustment is done prior to Nuke build as OCTOVERSION information is included in the result package.
+      - name: Append OCTOVERSION_CurrentBranch with -nightly (for scheduled)
+        if: github.event_name == 'schedule'
+        run: echo "OCTOVERSION_CurrentBranch=${{ env.OCTOVERSION_CurrentBranch }}-nightly" >> $GITHUB_ENV
+
       - name: Nuke Build 🏗
         id: build
         env:
-          OCTOVERSION_CurrentBranch: ${{ github.head_ref || github.ref }} # For pull_request events we override the /refs/pull/xx/merge branch to the PR's head branch
           OCTOVERSION_Patch: ${{ github.run_number }}
         shell: bash
         run: ./build.sh --verbosity verbose
 
-      - name: Install Octopus CLI 🐙
-        uses: OctopusDeploy/install-octopus-cli-action@v1
+      - name: Linux unit test report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          version: latest
-        
-      - name: Push to Octopus 🐙
-        uses: OctopusDeploy/push-package-action@v1
-        with:
-          server: ${{ secrets.DEPLOY_URL }}
-          space: Core Platform
-          api_key: ${{ secrets.DEPLOY_API_KEY }}
-          packages: |
-            ./artifacts/Octopus.Server.Extensibility.${{ steps.build.outputs.octoversion_fullsemver }}.nupkg          
+          name: Linux unit test results
+          path: ./TestResults/*.trx
+          reporter: dotnet-trx
+          fail-on-error: true
 
-      - name: Create Release in Octopus 🐙
-        uses: OctopusDeploy/create-release-action@v1
-        with:
-          server: ${{ secrets.DEPLOY_URL }}
-          space: Core Platform
-          api_key: ${{ secrets.DEPLOY_API_KEY }}
-          project: "ServerExtensibility"
-          packages: |
-            Octopus.Server.Extensibility:${{ steps.build.outputs.octoversion_fullsemver }}
-        
       - name: Tag release (when not pre-release) 🏷️
-        if: ${{ !contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
+        if: ${{ github.event_name != 'schedule' && !contains( steps.build.outputs.octoversion_fullsemver, '-' ) }}
         uses: actions/github-script@v3
         with:
           github-token: ${{ github.token }}
@@ -71,3 +63,38 @@ jobs:
               ref: "refs/tags/${{ steps.build.outputs.octoversion_fullsemver }}",
               sha: context.sha
             })
+
+      - name: Install Octopus CLI 🐙
+        uses: OctopusDeploy/install-octopus-cli-action@v1
+        with:
+          version: latest
+
+      - name: Set Octopus Related ENV
+        #Set Octopus Deploy Space Name
+        #Set Octopus Deploy Project Name
+        #Set Package Name
+        #GITHUB_REPOSITORY returns owner/repo-name. This will strip owner and retain repo-name.
+        run: |
+          echo "OCTOPUSDEPLOY_Space=Core Platform" >> $GITHUB_ENV
+          echo "OCTOPUSDEPLOY_Project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
+          echo "OCTOPUSDEPLOY_Package=Octopus.Server.Extensibility" >> $GITHUB_ENV 
+        
+      - name: Push to Octopus 🐙
+        uses: OctopusDeploy/push-package-action@v1
+        with:
+          server: ${{ secrets.DEPLOY_URL }}
+          space: ${{ env.OCTOPUSDEPLOY_Space }}
+          api_key: ${{ secrets.DEPLOY_API_KEY }}
+          packages: |
+            ./artifacts/${{ env.OCTOPUSDEPLOY_Package }}.${{ steps.build.outputs.octoversion_fullsemver }}.nupkg          
+
+      - name: Create Release in Octopus 🐙
+        uses: OctopusDeploy/create-release-action@v1
+        with:
+          server: ${{ secrets.DEPLOY_URL }}
+          space: ${{ env.OCTOPUSDEPLOY_Space }}
+          api_key: ${{ secrets.DEPLOY_API_KEY }}
+          project: ${{ env.OCTOPUSDEPLOY_Project }}
+          packages: |
+            ${{ env.OCTOPUSDEPLOY_Package }}:${{ steps.build.outputs.octoversion_fullsemver }}
+  
